GIMP Remake: gimp::Document Class Reference
gimp::Document Class Reference abstract
Abstract interface for an image document with layers.
#include <core/document.h>
Public Member Functions
virtual std::shared_ptr< Layer > add_layer ()=0
Adds a new layer to the document.
virtual void remove_layer (const std::shared_ptr< Layer > &layer)=0
Removes a layer from the document.
virtual const LayerStack & layers () const =0
Returns the layer stack.
virtual TileStore & tile_store ()=0
Returns the tile store for dirty region tracking.
virtual int width () const =0
Returns the document width in pixels.
virtual int height () const =0
Returns the document height in pixels.
Detailed Description
Abstract interface for an image document with layers.
Definition at line 22 of file document.h.
Member Function Documentation
add_layer()
virtual std::shared_ptr< Layer > gimp::Document::add_layer () pure virtual
Adds a new layer to the document.
Returns
Shared pointer to the created layer.
Postcondition
layers().count() is incremented by 1.
Returned pointer is non-null.
Implemented in gimp::ProjectFile.
height()
virtual int gimp::Document::height () const pure virtual
Returns the document height in pixels.
Implemented in gimp::ProjectFile.
Referenced by gimp::SkiaRenderer::render().
layers()
virtual const LayerStack & gimp::Document::layers () const pure virtual
Returns the layer stack.
Implemented in gimp::ProjectFile.
Referenced by gimp::SkiaRenderer::render().
remove_layer()
virtual void gimp::Document::remove_layer (const std::shared_ptr< Layer > & layer) pure virtual
Removes a layer from the document.
Parameters
layer The layer to remove.
Precondition
layer must exist in the document.
Postcondition
layers().count() is decremented by 1.
Implemented in gimp::ProjectFile.
tile_store()
virtual TileStore & gimp::Document::tile_store () pure virtual
Returns the tile store for dirty region tracking.
Implemented in gimp::ProjectFile.
width()
virtual int gimp::Document::width () const pure virtual
Returns the document width in pixels.
Implemented in gimp::ProjectFile.
Referenced by gimp::SkiaRenderer::render().
The documentation for this class was generated from the following file:
include/core/document.h