GIMP Remake: gimp::SkiaRenderer Class Reference
gimp::SkiaRenderer Class Reference
Renders documents using the Skia graphics library.
#include <render/skia_renderer.h>
Public Member Functions
void render (const Document &document) override
Renders the document to an internal surface.
sk_sp< SkImage > get_result ()
Returns the rendered result as a Skia image.
Detailed Description
Renders documents using the Skia graphics library.
Definition at line 23 of file skia_renderer.h.
Member Function Documentation
get_result()
sk_sp< SkImage > gimp::SkiaRenderer::get_result ()
Returns the rendered result as a Skia image.
Returns
The composited image, or nullptr if render() was not called.
Precondition
render() must have been called at least once.
Definition at line 44 of file skia_renderer.cpp.
render()
void gimp::SkiaRenderer::render (const Document & document) override virtual
Renders the document to an internal surface.
Parameters
document The document to render.
Precondition
document.width() > 0 and document.height() > 0.
Postcondition
get_result() returns the rendered image.
Implements gimp::Renderer.
Definition at line 22 of file skia_renderer.cpp.
References gimp::Document::height(), gimp::Document::layers(), and gimp::Document::width().
The documentation for this class was generated from the following files:
include/render/skia_renderer.h
include/render/skia_renderer.cpp