GIMP Remake: gimp::Layer Class Reference
gimp::Layer Class Reference
A single compositable image layer with RGBA pixel data.
#include <core/layer.h>
Public Member Functions
Layer (int width, int height)
Constructs a layer with the given dimensions.
void set_name (const std::string &name)
Sets the layer name.
const std::string & name () const
Returns the layer name.
void set_visible (bool visible)
Sets layer visibility.
bool visible () const
Returns true if the layer is visible.
void set_opacity (float opacity)
Sets layer opacity (0.0 to 1.0).
float opacity () const
Returns the layer opacity.
void set_blend_mode (BlendMode mode)
Sets the blend mode.
BlendMode blend_mode () const
Returns the blend mode.
int width () const
Returns the layer width.
int height () const
Returns the layer height.
std::vector< uint8_t > & data ()
Returns mutable access to pixel data (RGBA, 4 bytes per pixel).
const std::vector< uint8_t > & data () const
Returns const access to pixel data.
Detailed Description
A single compositable image layer with RGBA pixel data.
Definition at line 33 of file layer.h.
Constructor & Destructor Documentation
Layer()
gimp::Layer::Layer (int width, int height) inline
Constructs a layer with the given dimensions.
Parameters
width Layer width in pixels.
height Layer height in pixels.
Definition at line 42 of file layer.h.
References height(), and width().
Member Function Documentation
blend_mode()
BlendMode gimp::Layer::blend_mode () const inline
Returns the blend mode.
Definition at line 69 of file layer.h.
data() [1/2]
std::vector< uint8_t > & gimp::Layer::data () inline
Returns mutable access to pixel data (RGBA, 4 bytes per pixel).
Definition at line 78 of file layer.h.
data() [2/2]
const std::vector< uint8_t > & gimp::Layer::data () const inline
Returns const access to pixel data.
Definition at line 81 of file layer.h.
height()
int gimp::Layer::height () const inline
Returns the layer height.
Definition at line 75 of file layer.h.
Referenced by Layer().
name()
const std::string & gimp::Layer::name () const inline
Returns the layer name.
Definition at line 51 of file layer.h.
Referenced by set_name().
opacity()
float gimp::Layer::opacity () const inline
Returns the layer opacity.
Definition at line 63 of file layer.h.
Referenced by set_opacity().
set_blend_mode()
void gimp::Layer::set_blend_mode (BlendMode mode) inline
Sets the blend mode.
Definition at line 66 of file layer.h.
set_name()
void gimp::Layer::set_name (const std::string & name) inline
Sets the layer name.
Definition at line 48 of file layer.h.
References name().
set_opacity()
void gimp::Layer::set_opacity (float opacity) inline
Sets layer opacity (0.0 to 1.0).
Definition at line 60 of file layer.h.
References opacity().
set_visible()
void gimp::Layer::set_visible (bool visible) inline
Sets layer visibility.
Definition at line 54 of file layer.h.
References visible().
visible()
bool gimp::Layer::visible () const inline
Returns true if the layer is visible.
Definition at line 57 of file layer.h.
Referenced by set_visible().
width()
int gimp::Layer::width () const inline
Returns the layer width.
Definition at line 72 of file layer.h.
Referenced by Layer().
The documentation for this class was generated from the following file:
include/core/layer.h