GIMP Remake: gimp::ProjectFile Class Reference
gimp::ProjectFile Class Reference
Concrete implementation of Document for saveable project files.
#include <io/project_file.h>
Public Member Functions
ProjectFile (int w, int h)
Constructs a new project with the given dimensions.
std::shared_ptr< gimp::Layer > add_layer () override
Adds a new layer to the project.
void remove_layer (const std::shared_ptr< gimp::Layer > &layer) override
Removes a layer from the project.
const gimp::LayerStack & layers () const override
Returns the layer stack.
gimp::TileStore & tile_store () override
Returns the tile store for dirty region tracking.
int width () const override
Returns the canvas width in pixels.
int height () const override
Returns the canvas height in pixels.
Detailed Description
Concrete implementation of Document for saveable project files.
Manages layers and provides serialization support for project import/export.
Definition at line 23 of file project_file.h.
Constructor & Destructor Documentation
ProjectFile()
gimp::ProjectFile::ProjectFile (int w, int h) inline
Constructs a new project with the given dimensions.
Parameters
w Canvas width in pixels.
h Canvas height in pixels.
Definition at line 30 of file project_file.h.
Member Function Documentation
add_layer()
std::shared_ptr< gimp::Layer > gimp::ProjectFile::add_layer () inline override virtual
Adds a new layer to the project.
Returns
Shared pointer to the newly created layer.
Implements gimp::Document.
Definition at line 38 of file project_file.h.
height()
int gimp::ProjectFile::height () const inline nodiscard override virtual
Returns the canvas height in pixels.
Implements gimp::Document.
Definition at line 64 of file project_file.h.
Referenced by gimp::IOManager::exportProject().
layers()
const gimp::LayerStack & gimp::ProjectFile::layers () const inline nodiscard override virtual
Returns the layer stack.
Implements gimp::Document.
Definition at line 55 of file project_file.h.
Referenced by gimp::IOManager::exportProject().
remove_layer()
void gimp::ProjectFile::remove_layer (const std::shared_ptr< gimp::Layer > & layer) inline override virtual
Removes a layer from the project.
Parameters
layer The layer to remove.
Implements gimp::Document.
Definition at line 49 of file project_file.h.
tile_store()
gimp::TileStore & gimp::ProjectFile::tile_store () inline override virtual
Returns the tile store for dirty region tracking.
Implements gimp::Document.
Definition at line 58 of file project_file.h.
width()
int gimp::ProjectFile::width () const inline nodiscard override virtual
Returns the canvas width in pixels.
Implements gimp::Document.
Definition at line 61 of file project_file.h.
Referenced by gimp::IOManager::exportProject().
The documentation for this class was generated from the following file:
include/io/project_file.h