GIMP Remake: gimp::IOManager Class Reference
gimp::IOManager Class Reference
Handles file I/O operations for images and project files.
#include <io/io_manager.h>
Public Member Functions
ProjectFile importProject (const std::string &file_path)
Imports a project from a JSON file.
bool exportProject (const ProjectFile &project, const std::string &file_path)
Exports a project to a JSON file.
ImageFile readImage (const std::string &file_path)
Reads an image file from disk.
bool writeImage (const cv::Mat &mat, const std::string &file_path)
Writes an image to disk.
void toGrayscale (cv::Mat &mat)
Converts an image to grayscale in-place.
void toRgb (cv::Mat &mat)
Converts an image to RGB in-place.
void toRgba (cv::Mat &mat)
Converts an image to RGBA in-place.
Detailed Description
Handles file I/O operations for images and project files.
Definition at line 24 of file io_manager.h.
Member Function Documentation
exportProject()
bool gimp::IOManager::exportProject (const ProjectFile & project, const std::string & file_path)
Exports a project to a JSON file.
Parameters
project The project to export.
file_path Destination file path.
Returns
True on success, false on failure.
Definition at line 66 of file io_manager.cpp.
References gimp::ProjectFile::height(), gimp::ProjectFile::layers(), and gimp::ProjectFile::width().
importProject()
ProjectFile gimp::IOManager::importProject (const std::string & file_path)
Imports a project from a JSON file.
Parameters
file_path Path to the project file.
Returns
The loaded ProjectFile.
Exceptions
std::runtime_error If file cannot be opened or data is invalid.
Definition at line 23 of file io_manager.cpp.
readImage()
ImageFile gimp::IOManager::readImage (const std::string & file_path)
Reads an image file from disk.
Parameters
file_path Path to the image file.
Returns
ImageFile containing the loaded image data.
Precondition
file_path must be a valid, accessible file path.
Postcondition
If successful, returned ImageFile::empty() is false.
Definition at line 107 of file io_manager.cpp.
toGrayscale()
void gimp::IOManager::toGrayscale (cv::Mat & mat)
Converts an image to grayscale in-place.
Parameters
mat The image to convert (modified in-place).
Definition at line 118 of file io_manager.cpp.
toRgb()
void gimp::IOManager::toRgb (cv::Mat & mat)
Converts an image to RGB in-place.
Parameters
mat The image to convert (modified in-place).
Definition at line 130 of file io_manager.cpp.
toRgba()
void gimp::IOManager::toRgba (cv::Mat & mat)
Converts an image to RGBA in-place.
Parameters
mat The image to convert (modified in-place).
Definition at line 142 of file io_manager.cpp.
writeImage()
bool gimp::IOManager::writeImage (const cv::Mat & mat, const std::string & file_path)
Writes an image to disk.
Parameters
mat The image matrix to write.
file_path Destination file path.
Returns
True on success, false on failure.
Precondition
mat must not be empty.
file_path must be a writable location.
Definition at line 113 of file io_manager.cpp.
The documentation for this class was generated from the following files:
include/io/io_manager.h
src/io/io_manager.cpp