GIMP Remake: gimp::error::ErrorInfo Class Reference
gimp::error::ErrorInfo Class Reference
Error information container.
#include <error_handling/error_result.h>
Public Member Functions
ErrorInfo ()
Construct an ErrorInfo for a successful operation.
ErrorInfo (ErrorCode code, const std::string &context="")
Construct an ErrorInfo from an error code.
ErrorInfo (ErrorCode code, ErrorCategory category, ErrorSeverity severity, const std::string &message)
Construct an ErrorInfo with custom categorization.
ErrorCode GetCode () const
ErrorCategory GetCategory () const
ErrorSeverity GetSeverity () const
const std::string & GetMessage () const
bool IsSuccess () const
Check if this represents a successful operation.
bool IsFatal () const
Check if this error is fatal.
bool IsRecoverable () const
Check if this error is recoverable.
std::string ToString () const
Get a formatted error string.
Detailed Description
Error information container.
Holds detailed information about an error, including the error code, category, severity, and optional context message.
Definition at line 25 of file error_result.h.
Constructor & Destructor Documentation
ErrorInfo() [1/3]
gimp::error::ErrorInfo::ErrorInfo () inline
Construct an ErrorInfo for a successful operation.
Definition at line 30 of file error_result.h.
References Info.
ErrorInfo() [2/3]
gimp::error::ErrorInfo::ErrorInfo (ErrorCode code, const std::string & context = "") inline explicit
Construct an ErrorInfo from an error code.
Parameters
code The error code
context Additional context about the error (optional)
Definition at line 43 of file error_result.h.
ErrorInfo() [3/3]
gimp::error::ErrorInfo::ErrorInfo (ErrorCode code, ErrorCategory category, ErrorSeverity severity, const std::string & message) inline
Construct an ErrorInfo with custom categorization.
Parameters
code The error code
category The error category
severity The error severity
message Custom error message
Definition at line 61 of file error_result.h.
Member Function Documentation
GetCategory()
ErrorCategory gimp::error::ErrorInfo::GetCategory () const inline
Definition at line 74 of file error_result.h.
GetCode()
ErrorCode gimp::error::ErrorInfo::GetCode () const inline
Definition at line 73 of file error_result.h.
GetMessage()
const std::string & gimp::error::ErrorInfo::GetMessage () const inline
Definition at line 76 of file error_result.h.
GetSeverity()
ErrorSeverity gimp::error::ErrorInfo::GetSeverity () const inline
Definition at line 75 of file error_result.h.
IsFatal()
bool gimp::error::ErrorInfo::IsFatal () const inline
Check if this error is fatal.
Returns
true if the error is fatal
Definition at line 88 of file error_result.h.
IsRecoverable()
bool gimp::error::ErrorInfo::IsRecoverable () const inline
Check if this error is recoverable.
Returns
true if the error is recoverable
Definition at line 94 of file error_result.h.
IsSuccess()
bool gimp::error::ErrorInfo::IsSuccess () const inline
Check if this represents a successful operation.
Returns
true if no error occurred
Definition at line 82 of file error_result.h.
Referenced by ToString().
ToString()
std::string gimp::error::ErrorInfo::ToString () const inline
Get a formatted error string.
Returns
Formatted error message with category and severity
Definition at line 100 of file error_result.h.
References IsSuccess().
Referenced by setupErrorRecoveryHandlers().
The documentation for this class was generated from the following file:
include/error_handling/error_result.h