GIMP Remake: gimp::error::Result< T > Class Template Reference
gimp::error::Result< T > Class Template Reference
Result<T> type for error-aware return values.
#include <error_handling/error_result.h>
Public Member Functions
Result (T value)
Construct a successful Result with a value.
Result (ErrorInfo error)
Construct a failed Result with an error.
Result (ErrorCode code, const std::string &context="")
Construct a failed Result from an error code.
bool IsOk () const
Check if the Result contains a value (success).
bool IsError () const
Check if the Result contains an error (failure).
T & Value () &
Get the value (assumes IsOk() is true).
const T & Value () const &
Get the value (assumes IsOk() is true).
T && Value () &&
Move the value out (assumes IsOk() is true).
const ErrorInfo & Error () const
Get the error information (assumes IsError() is true).
T ValueOr (T default_value) const &
Get the value or a default if error.
T ValueOr (T default_value) &&
Get the value or a default if error (move version).
template<typename F>
auto Map (F &&func) const &-> Result< decltype(func(std::declval< T >()))>
Map the value if Ok, otherwise propagate error.
operator bool () const
Convert to bool (true if Ok).
Detailed Description
template<typename T>
class gimp::error::Result< T >
Result<T> type for error-aware return values.
A Result<T> can hold either a value of type T (success) or an ErrorInfo (failure). This allows functions to return errors without throwing exceptions.
Example usage:
Result<int> Divide(int a, int b) {
    if (b == 0) {
        return ErrorInfo(ErrorCode::InvalidArgumentOutOfRange, "Division by zero");
    }
    return a / b;
}
auto result = Divide(10, 2);
if (result.IsOk()) {
    std::cout << "Result: " << result.Value() << std::endl;
} else {
    std::cerr << "Error: " << result.Error().GetMessage() << std::endl;
}
Definition at line 148 of file error_result.h.
Constructor & Destructor Documentation
Result() [1/3]
template<typename T> gimp::error::Result< T >::Result (T value) inline
Construct a successful Result with a value.
Parameters
value The success value
Definition at line 154 of file error_result.h.
Referenced by Map().
Result() [2/3]
template<typename T> gimp::error::Result< T >::Result (ErrorInfo error) inline
Construct a failed Result with an error.
Parameters
error The error information
Definition at line 160 of file error_result.h.
Result() [3/3]
template<typename T> gimp::error::Result< T >::Result (ErrorCode code, const std::string & context = "") inline
Construct a failed Result from an error code.
Parameters
code The error code
context Additional context (optional)
Definition at line 167 of file error_result.h.
Member Function Documentation
Error()
template<typename T> const ErrorInfo & gimp::error::Result< T >::Error () const inline
Get the error information (assumes IsError() is true).
Returns
Reference to the error information
Exceptions
std::bad_variant_access if called on a success Result
Definition at line 207 of file error_result.h.
Referenced by Map().
IsError()
template<typename T> bool gimp::error::Result< T >::IsError () const inline
Check if the Result contains an error (failure).
Returns
true if the operation failed
Definition at line 179 of file error_result.h.
IsOk()
template<typename T> bool gimp::error::Result< T >::IsOk () const inline
Check if the Result contains a value (success).
Returns
true if the operation was successful
Definition at line 173 of file error_result.h.
Referenced by Map(), operator bool(), gimp::error::Result< void >::operator bool(), ValueOr(), and ValueOr().
Map()
template<typename T> template<typename F> auto gimp::error::Result< T >::Map (F && func) const & -> Result< decltype(func(std::declval< T >()))> inline
Map the value if Ok, otherwise propagate error.
Template Parameters
F Function type
Parameters
func Function to apply to the value
Returns
New Result with transformed value or same error
Definition at line 242 of file error_result.h.
References Error(), IsOk(), Result(), and Value().
operator bool()
template<typename T> gimp::error::Result< T >::operator bool () const inline explicit
Convert to bool (true if Ok).
Returns
true if the Result contains a value
Definition at line 255 of file error_result.h.
References IsOk().
Value() [1/3]
template<typename T> T & gimp::error::Result< T >::Value () & inline
Get the value (assumes IsOk() is true).
Returns
Reference to the value
Exceptions
std::bad_variant_access if called on an error Result
Definition at line 186 of file error_result.h.
Referenced by Map(), and ValueOr().
Value() [2/3]
template<typename T> T && gimp::error::Result< T >::Value () && inline
Move the value out (assumes IsOk() is true).
Returns
Moved value
Exceptions
std::bad_variant_access if called on an error Result
Definition at line 200 of file error_result.h.
Value() [3/3]
template<typename T> const T & gimp::error::Result< T >::Value () const & inline
Get the value (assumes IsOk() is true).
Returns
Const reference to the value
Exceptions
std::bad_variant_access if called on an error Result
Definition at line 193 of file error_result.h.
ValueOr() [1/2]
template<typename T> T gimp::error::Result< T >::ValueOr (T default_value) && inline
Get the value or a default if error (move version).
Parameters
default_value The default value to return on error
Returns
The value or default
Definition at line 227 of file error_result.h.
References IsOk().
ValueOr() [2/2]
template<typename T> T gimp::error::Result< T >::ValueOr (T default_value) const & inline
Get the value or a default if error.
Parameters
default_value The default value to return on error
Returns
The value or default
Definition at line 214 of file error_result.h.
References IsOk(), and Value().
The documentation for this class was generated from the following file:
include/error_handling/error_result.h