GIMP Remake: gimp::error::ErrorHandler Class Reference
gimp::error::ErrorHandler Class Reference
Application-wide error handler singleton.
#include <error_handling/error_handler.h>
Public Member Functions
ErrorHandler (const ErrorHandler &)=delete
ErrorHandler & operator= (const ErrorHandler &)=delete
ErrorHandler (ErrorHandler &&)=delete
ErrorHandler & operator= (ErrorHandler &&)=delete
void Initialize ()
Initialize the error handler.
void Shutdown ()
Shutdown the error handler.
void ReportError (const ErrorInfo &error)
Report an error.
void ReportError (ErrorCode code, const std::string &context="")
Report an error from an error code.
void HandleFatalError (const ErrorInfo &error)
Handle a fatal error.
bool AttemptRecovery (const ErrorInfo &error)
Attempt to recover from an error.
void RegisterCallback (ErrorCallback callback, ErrorCategory category=ErrorCategory::Unknown)
Register an error callback.
void RegisterRecoveryHandler (ErrorCategory category, RecoveryCallback callback)
Register a recovery handler.
ErrorInfo GetLastError () const
Get the last reported error.
std::vector< ErrorInfo > GetErrorHistory () const
Get all errors reported since initialization.
void ClearHistory ()
Clear error history.
void SetShowErrorDialogs (bool show)
Set whether to show error dialogs to the user.
bool GetShowErrorDialogs () const
Check if error dialogs are enabled.
void SetLogFilePath (const std::string &path)
Set the error log file path.
std::string GetLogFilePath () const
Get the error log file path.
Static Public Member Functions
static ErrorHandler & GetInstance ()
Get the singleton instance.
Detailed Description
Application-wide error handler singleton.
The ErrorHandler manages all error reporting, logging, and recovery throughout the application. It provides:
Centralized error logging
Fatal vs recoverable error handling
Crash handling and safe shutdown
Error recovery mechanisms
Error callback registration
Definition at line 53 of file error_handler.h.
Member Function Documentation
AttemptRecovery()
bool gimp::error::ErrorHandler::AttemptRecovery (const ErrorInfo & error)
Attempt to recover from an error.
Invokes registered recovery callbacks for the error category.
Parameters
error The error to recover from
Returns
true if recovery was successful, false otherwise
Definition at line 161 of file error_handler.cpp.
Referenced by ReportError().
ClearHistory()
void gimp::error::ErrorHandler::ClearHistory ()
Clear error history.
Definition at line 205 of file error_handler.cpp.
GetErrorHistory()
std::vector< ErrorInfo > gimp::error::ErrorHandler::GetErrorHistory () const
Get all errors reported since initialization.
Returns
Vector of all reported errors
Definition at line 199 of file error_handler.cpp.
GetInstance()
ErrorHandler & gimp::error::ErrorHandler::GetInstance () static
Get the singleton instance.
Returns
Reference to the ErrorHandler instance
Definition at line 27 of file error_handler.cpp.
Referenced by setupErrorRecoveryHandlers().
GetLastError()
ErrorInfo gimp::error::ErrorHandler::GetLastError () const
Get the last reported error.
Returns
The most recent error, or a success ErrorInfo if none
Definition at line 190 of file error_handler.cpp.
GetLogFilePath()
std::string gimp::error::ErrorHandler::GetLogFilePath () const
Get the error log file path.
Returns
Path to the error log file
Definition at line 229 of file error_handler.cpp.
GetShowErrorDialogs()
bool gimp::error::ErrorHandler::GetShowErrorDialogs () const
Check if error dialogs are enabled.
Returns
true if dialogs will be shown
Definition at line 217 of file error_handler.cpp.
HandleFatalError()
void gimp::error::ErrorHandler::HandleFatalError (const ErrorInfo & error)
Handle a fatal error.
This will attempt to save any unsaved work, flush logs, and terminate the application safely.
Parameters
error The fatal error information
Definition at line 129 of file error_handler.cpp.
Initialize()
void gimp::error::ErrorHandler::Initialize ()
Initialize the error handler.
This should be called early in application startup to set up crash handlers and error logging.
Definition at line 48 of file error_handler.cpp.
RegisterCallback()
void gimp::error::ErrorHandler::RegisterCallback (ErrorCallback callback, ErrorCategory category = ErrorCategory::Unknown)
Register an error callback.
Callbacks are invoked whenever an error is reported, allowing different parts of the application to respond to errors.
Parameters
callback The callback function
category Only invoke for errors in this category (optional)
Definition at line 178 of file error_handler.cpp.
Referenced by setupErrorRecoveryHandlers().
RegisterRecoveryHandler()
void gimp::error::ErrorHandler::RegisterRecoveryHandler (ErrorCategory category, RecoveryCallback callback)
Register a recovery handler.
Recovery handlers are invoked when attempting to recover from errors in a specific category.
Parameters
category The error category to handle
callback The recovery callback
Definition at line 184 of file error_handler.cpp.
Referenced by setupErrorRecoveryHandlers().
ReportError() [1/2]
void gimp::error::ErrorHandler::ReportError (const ErrorInfo & error)
Report an error.
This is the main entry point for error reporting. Based on the error severity, it will either:
Log the error (Info/Warning)
Attempt recovery (Recoverable)
Initiate safe shutdown (Fatal)
Parameters
error The error to report
Definition at line 80 of file error_handler.cpp.
References AttemptRecovery().
Referenced by ReportError().
ReportError() [2/2]
void gimp::error::ErrorHandler::ReportError (ErrorCode code, const std::string & context = "")
Report an error from an error code.
Parameters
code The error code
context Additional context (optional)
Definition at line 124 of file error_handler.cpp.
References ReportError().
SetLogFilePath()
void gimp::error::ErrorHandler::SetLogFilePath (const std::string & path)
Set the error log file path.
Parameters
path Path to the error log file
Definition at line 223 of file error_handler.cpp.
SetShowErrorDialogs()
void gimp::error::ErrorHandler::SetShowErrorDialogs (bool show)
Set whether to show error dialogs to the user.
Parameters
show true to show dialogs, false to suppress
Definition at line 211 of file error_handler.cpp.
Shutdown()
void gimp::error::ErrorHandler::Shutdown ()
Shutdown the error handler.
Flushes any pending error logs and cleans up resources.
Definition at line 64 of file error_handler.cpp.
The documentation for this class was generated from the following files:
include/error_handling/error_handler.h
src/error_handling/error_handler.cpp